class SimpleProviderAdapter:
    def __init__(self, provider: str) -> None:
        self.provider = provider

    def validate_credentials(self, api_key: str) -> bool:
        return api_key.startswith("ai_") and "invalid" not in api_key

    def generate_decision(self, symbol: str, timeframe: str, prompt: str) -> dict:
        if "provider_fail" in prompt or symbol == "FAILUSDT":
            raise RuntimeError("provider_unavailable")

        action = "BUY" if symbol.startswith("BTC") else "HOLD"
        confidence = 0.78 if action == "BUY" else 0.52
        return {
            "action": action,
            "confidence": confidence,
            "riskLevel": "MEDIUM",
            "status": "PENDING_APPROVAL",
            "symbol": symbol,
            "timeframe": timeframe,
            "reasoning": f"Generated by {self.provider}",
        }


def get_provider_adapter(provider: str) -> SimpleProviderAdapter:
    if provider not in {"OPENAI", "GROQ", "DEEPSEEK", "GEMINI"}:
        raise ValueError("unsupported_provider")
    return SimpleProviderAdapter(provider)
